# CSCI 513.01W – Python Programming for AI
## Assignment 4 - NumPy

## Exercise I

Create an array called prices of 50 random float numbers between 0 and 100 (inclusive).

In [67]:
import numpy as np

prices_int = np.random.randint(0, 101, 50)
print(prices_int)
prices_float = np.random.random([50])
print(prices_float)

[68 84 56 13 55 45 98  2 42 58 68 55 32 36 90 81  2 42 97  8 43 85 51 29
 78 27 34 15 62  0 69 52 37 99 88 96 13 13 37 22 25 55 29 17 38 96 76 79
 11 58]
[0.36527602 0.67735053 0.26475875 0.97983765 0.55006717 0.01743548
 0.62459805 0.22624872 0.47604426 0.55146221 0.56087226 0.36900841
 0.23863672 0.52342365 0.89607338 0.9454461  0.26979457 0.29058174
 0.13220978 0.79580354 0.5881784  0.77347068 0.33387661 0.96265076
 0.34732802 0.09826086 0.74232339 0.95765172 0.77578535 0.18715396
 0.23815106 0.64290929 0.93013638 0.17733469 0.00224873 0.00207409
 0.53634787 0.09906552 0.28424114 0.48352484 0.21879908 0.01876884
 0.82328814 0.0964693  0.32615866 0.08636867 0.46225661 0.09494839
 0.93889761 0.41702363]


## Exercise II
- Create a NumPy array called ages. This array should have 15 random ages between 5 and 25 (inclusive)
- Create a NumPy array called ages2. The values in ages2 should be double the ones in ages.

In [68]:
import numpy as np

ages = np.random.randint(5, 26, 15)
print(ages)
ages2 = ages * 2
print(ages2)

[ 7 16 11  8 17 21 15 17 15  5 25 23 17 22  6]
[14 32 22 16 34 42 30 34 30 10 50 46 34 44 12]


## Exercise III

To make ages2 a little bit more realistic, insert a little random noise into each element of the array you created. To be more precise, modify each value assigned to ages2 by adding a different random floating-point value between -2 and +2.

In [69]:
import numpy as np 

ages2 = ages * 2
print('age double:', ages2)

noise = np.random.randint(-2, +2, 15)
print('noise:', noise)

ages2_mod = ages2 + noise
print('Age with noise:', ages2_mod)

age double: [14 32 22 16 34 42 30 34 30 10 50 46 34 44 12]
noise: [-2  1 -2  1  1 -1  1  1  0 -2  1  1 -1  0  1]
Age with noise: [12 33 20 17 35 41 31 35 30  8 51 47 33 44 13]


# Exercise IV
Suppose we have two numpy arrays that represent the price of the same items from different stores:

store1 = np.array([29, 4, 2, 30, 15, 48, 63, 32, 53, 70, 47, 19, 24])

store2 = np.array([23, 2, 12, 32, 25, 47, 53, 39, 63, 71, 47, 18, 21])

Create a new array where we take the value from store1 whenever the corresponding value in cond is True, otherwise we take the value from store2.

cond = np.array([False, True, False, False, False, True, False, False, True, True, False, False, True])

In [70]:
store1 = np.array([29, 4, 2, 30, 15, 48, 63, 32, 53, 70, 47, 19, 24])

store2 = np.array([23, 2, 12, 32, 25, 47, 53, 39, 63, 71, 47, 18, 21])

cond = np.array([False, True, False, False, False, True, False, False, True, True, False, False, True])

combo_prices = np.array([cond, store1, store2])

# Exercise V

Solve Exercise IV using numpy where function.

In [71]:
combo_prices = np.where(cond, store1, store2)
print(combo_prices)

[23  4 12 32 25 48 53 39 53 70 47 18 24]


# Exercise VI

Suppose we have the scores from players playing an arcade game:

scores = np.random.randint(low=0, high=70, size=[2000])

1. Retrieve the scores that are greater than 20.
2. Retrieve the scores that are not 30.
3. Retrieve the average score.
4. Retrieve the minimum score.
5. Retrieve the maximum score.

In [72]:
scores = np.random.randint(0, 70, [2000])
print('score > 20:', scores[scores>20])

print('score not 30:', scores != 30)

average = np.mean(scores)
print('average:', average)

min_value = min(scores)
print('minimum score:', min_value)

max_value = max(scores)
print('maximum score:', max_value)

score > 20: [33 57 63 ... 23 53 42]
score not 30: [ True  True  True ...  True  True  True]
average: 35.324
minimum score: 0
maximum score: 69
